package model;

public enum TypeMesure {
    TEMPERATURE,
    HUMIDITE,
    PRESSION,
    LUMINOSITE,
    PH,
    NUTRIMENTS,
    SALINITE,
    FREQUENCE_CARDIAQUE,
    TEMPERATURE_CORPORELLE,
    SATURATION_O2
}
